name: Trigger auto deployment for get-started

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/get-started-AutoDeployTrigger-87396dd4-4e3b-4e7e-b45b-7790bea7ad15.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cabe548f70b1acr.azurecr.io
          username: ${{ secrets.GETSTARTED_REGISTRY_USERNAME }}
          password: ${{ secrets.GETSTARTED_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cabe548f70b1acr.azurecr.io/get-started:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GETSTARTED_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n get-started -g madsstorm_rg_2132 --server cabe548f70b1acr.azurecr.io --username  ${{ secrets.GETSTARTED_REGISTRY_USERNAME }} --password ${{ secrets.GETSTARTED_REGISTRY_PASSWORD }}
            az containerapp update -n get-started -g madsstorm_rg_2132 --image cabe548f70b1acr.azurecr.io/get-started:${{ github.sha }}
